language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

install:
  - ./gradlew setupCiWorkspace

script:
  - ./gradlew build

deploy:
  provider: releases
  api_key: "${AC_TOKEN}"
  file_glob: true
  file:
    - build/libs/*
  skip_cleanup: true
  name: "5.0-RC-${TRAVIS_BUILD_NUMBER}"
